### ISSUE TITLE
The pom.xml is missing

### ISSUE THREAD

**Issue by bbrudnoy** [ronanquillevere/gwtrestapp#1]
To be able to `mvn` anything (e.g. `mvn eclipse:eclipse`, to generate Eclipse project files), pom.xml has to be present.

**Comment by ronanquillevere** [comment]
inside /src maybe :)

**Comment by bbrudnoy** [comment]
Vote to move pom.xml to project root, the canonical location for pom.xml files. Developers will be expecting to be able to execute `mvn` commands after `cd gwtrestapp`, without having to specify pom.xml location.

**Comment by ronanquillevere** [comment]
Life is full of expectations not satisfied :smile:

**Comment by bbrudnoy** [comment]
Sure, and customers will flock to those individuals, businesses, and projects, who meet and exceed their expectations.

**Comment by ronanquillevere** [comment]
Pull request is welcome :smile: beauty of open sourcing
